controller_manager:
  ros__parameters:
    update_rate: 100  # Tần số cập nhật 100Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - khau1_joint
      - khau2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity